### ISSUE TITLE
Support Reading the JWT from the Requests Cookies

### ISSUE THREAD

**Issue by cancan101** [GetBlimp/django-rest-framework-jwt#120]
Right now the `Authorization` header is read but the JWT could also be stored in a cookie.

**Comment by amsheehan** [comment]
@jpadilla Any timeline on this? Might be really useful with the recent surge of blogs about why not to use JWT's in SPA's :)

**Comment by jpadilla** [comment]
Closing this as I'm not entirely sure I'd want to support the use case out of the box. You could always subclass where needed to handle it. Opened to continue discussing it.

**Comment by angvp** [comment]
Hi, after reading this https://stormpath.com/blog/token-auth-spa/ I was wondering if we should re open this issue?

**Comment by kutakdogan** [comment]
Agreed, handling via cookie solves XSS issues, and given the cookie is passed by the browser, it would require no client-side code at all. Currently, token must be read by the client, and then `Authorization: Bearer XXX` must be set by the client.

Cookie approach opens up CSRF issues, but Django already handles this out of the box.

Security concerns alone seem to merit standard support for this?

**Comment by carltongibson** [comment]
Hmmm. I'm a little sceptical. There are security trade-offs however you do it: rhetorically, this is `DRF-JWT` — if that's not what you need don't use it...

* If we the cookie, what's the benefit to JWT over just using Django/DRF's session based authentication? 
* Can someone put together an example of how this would actually look? (A PR say?)
* If such an example existed, could that live in a separate repo, so the maintenance rested there and not here? (Such a repo could be linked from DRF and DRF-JWT docs.)

Note the "rhetorically" — it's a request for the case to be made.

**Comment by cancan101** [comment]
The JWT specification does not state how the JWT is to be transmitted. The spec gives examples of the HTTP header or query string but leave open other means. So I don't think supporting cookies is incompatible with `DRF-JWT`.

If you want to use JWT to secure a resource such as an image which is to be loaded via a `src` attribute, then you cannot use HTTP headers. Your options are cookies or query strings. Query strings have the downsides of 1) showing up in the logs and 2) can leak the JWT if the user shares the URL for the image.

As far as using what Django offers, the closest options would be `signed_cookies`. This seems like a non standards version of JWT (i.e. it is a form of bearer token). Why not just use JWT here?

**Comment by cancan101** [comment]
There is actually a [good example of how to do this in the docs](https://github.com/GetBlimp/django-rest-framework-jwt/blob/4628b06bf5975ddba9a126248b65422aea837070/docs/index.md#extending-jsonwebtokenauthentication) (right now it's for reading the JWT from the querystring but I imagine it could be adapted).

**Comment by carltongibson** [comment]
All of that makes sense — query strings always get a bad rap — but only addresses (part of) the example question. (The other part being the PR.)

Looking at the example this comes back to mind:

> You could always subclass where needed to handle it. 

There's no resource to work on this per se — so I'm not going to reopen the ticket right now — **but** if a documented etc PR turns up I'm very happy to look at it favourably. 

(I'm still not quite sure about why you'd want cookies but not, the built-in, session authentication — but no doubt you have reasons.)

**Comment by orf** [comment]
We have a use case that could benefit from this, our authentication is
handled by a Django app that returns a JWT and the client uses this to make
requests to a second server.

This works great but falls over if you want to secure images or other files
against non authenticated access as the browser won't send the JWT with the
request, leaving you with only one option: cookies.

**Comment by moises-silva** [comment]
@carltongibson PR #275 created. We solved this internally by subclassing (which I realize is the approach suggested here by @jpadilla). The code is significantly simpler to implement in DRF JWT and it'd reduce duplication as it's clear other people need this as well.

Our use case involves third-party applications that are authenticated using [nginx http auth request module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html). It'd be a lot of work (and involve a fork) to modify the third party application to send the Authorization header and in fact in some cases it might not even be possible or practical because when opening a new browser window you can't control the headers when setting that window.location property to go somewhere, even within your own domain, and I'd rather avoid passing the token in the query string. Using cookies gives us a seamless integration while still allowing us to continue to use the tokens in our many API front-ends.

**Comment by estaban** [comment]
Can we re-consider opening this issue? A pull request solving this has been created by moises-silva@ two months ago (see post above).

I am interested in this for a website I am creating where users authenticate to the server:
- If the user authenticates in one tab from the browser, then opens another one, he needs to log in again as the JWT token is not shared among tabs (http://stackoverflow.com/questions/30061307/jwt-how-to-handle-get-requests-when-user-opens-a-new-tab)
- (corollary of previous point) In order to log out, user needs to log out from all tabs.
