### ISSUE TITLE
Why token verification make db call ?

### ISSUE THREAD

**Issue by HarishAtGitHub** [GetBlimp/django-rest-framework-jwt#192]
I started to use this module in my project. It is really good. But one thing which bothers me is that when I verify the token it goes through this part of code (https://github.com/GetBlimp/django-rest-framework-jwt/blob/1.7.2/rest_framework_jwt/serializers.py#L98-L116)  and does 2 things

1. get username from payload
2. get_by_natural_key using username which is  a costly DB call

**why verify token needs to do point 2 ?**
only job is it not to check whether the token was not tampered, I think that is what the http://jwt.io/ does. also it does verify the signature.

I can understand that it is better to check if the user is valid(it will help in one scenario where user was deleted, but which is considered a rare scenario). but that again depends on single point of checking which will be hurdle when scaling . I thought that the main idea behind token auth was to scale by having necessary info in the token (which is untamperable). What is your view ?
Had it been done just like verifying token based on the secret key, I would just distribute the secret key to various servers having different services and make the validation done there itself instead of relying on a network/db call . [Similar point of view is also present here](http://www.django-rest-framework.org/api-guide/authentication/#json-web-token-authentication).

**why verify token needs point 1 ?**
why is there a need to enforce the presence of username in token. In my case there is only email id (which is valid case). May be the answer for first question will answer this question too as get_by_natural_key needs username.

also I have another doubt. 

**does this library support public key private key based signing of the token ?** 

(which will help me validate my token the first time using my public key in the client end whenever necessary, as private (secret) keys cannot be shared)

**Comment by jpadilla** [comment]
1. Regarding avoiding db queries. That is a benefit, though harshly the whole point. You're still avoiding a session store as well. This is meant to be a simple generic implementation for authentication with JWT. Not meant to be an all around highly scalable thing. Every project has its requirements, you can choose to extend our build your own. You could probably get away with creating a User object from the JWT instead of querying your DB and returning that.

2. The idea behind using `get_by_natural_key` is that if you have a custom user model you'd be able to modify that and `JWT_PAYLOAD_GET_USERNAME_HANDLER` similar to how Django authentication backends work.

3. Not yet but #200 is close.
