### ISSUE TITLE
Updating requirements/compat

### ISSUE THREAD

**Issue by carltongibson** [GetBlimp/django-rest-framework-jwt#216]
Hey @jpadilla! 

I need to use DRF-JWT in a project, so I have a bit of time. 

How would you feel about:

* Raising requirements to Django 1.8+
* Dropping DRF 2 support
* Dropping Python 2.6 and 3.2
* Adding Python 3.4 and 3.5

?

(Wanted to check first.)

**Comment by jpadilla** [comment]
@carltongibson oh yea, that'd be awesome!

**Comment by carltongibson** [comment]
@jpadilla Fine. Next couple of loops. 👍

**Comment by mblayman** [comment]
@jpadilla What would need to be done to get DRF-JWT up to supporting Django 1.9 and DRF 3.2+? Is there enough test coverage that if those things were added to the Travis matrix and any errors were fixed then it would be reasonable to say that those newer version are supported? Are there big known blockers that prevent support on those versions?

I'd like to help if I can, but I'm not sure where to get started.

**Comment by carltongibson** [comment]
@mblayman — I'd guess not much. First step is just to update the matrix and see what happens. Start there if you're happy.

**Comment by mblayman** [comment]
Looking at the test matrix on master, it seems that the only thing missing is Django 1.9 testing on Python 3.3. I'll try to put up a PR to get that fixed up.

I think there might be a couple other issues that the tests don't cover because I tried to run JWT on some newer versions (Python 2.7, Django 1.9, DRF 3.3) that did not seem to work. If I track them down, I can add them to a separate issue.

**Comment by carltongibson** [comment]
Django 1.9 doesn't support Python 3.3 https://docs.djangoproject.com/en/1.9/releases/1.9/

**Comment by carltongibson** [comment]
Closed by #224
