### ISSUE TITLE
request.user is Anon

### ISSUE THREAD

**Issue by genxstylez** [GetBlimp/django-rest-framework-jwt#228]
as titled

```python
@api_view(['POST'])
@permission_classes((IsAuthenticated))
def some_func(request):
    return HttpResponse(request.user.is_authenticated())
```

the above snippet returns False

What am I doing wrong?

**Comment by carltongibson** [comment]
Sorry, this isn't an issue. If you need support try Stack Overflow. I suggest you provide a fuller example there. You could have done any number of things wrong.

**Comment by AndrewJHart** [comment]
@genxstylez  See this issue here #45  I have some middleware in there that should solve the problem for you. However, be wary that if you are still using the DRF authentication then you will in effect be triggering authentication twice.. You could disable default DRF auth and use the `IsAuthenticated` permission class + the middleware posted in the other issue. 

Hope this helps.  

and FWIW @carltongibson  That was not a very helpful response man.. cmon? You can do better than that and if not then you should just save us all some time and stop posting.

**Comment by carltongibson** [comment]
> That was not a very helpful response man.. cmon? 

Sorry man but maintaining OSS is a battle for time — and no-one pays for it — it's all volunteer. Actual issues fine, no problem. Usage questions __really__ belong elsewhere. 

(The ticket doesn't even have enough to go on — A decent question will get a decent response 90% of the time, even if it is usage.)

**Comment by erichonkanen** [comment]
hey I think the question is valid and @AndrewJHart explained it well. I just ran into this (if I'm not mistaken I've run into it before). Should this package include a middleware that automatically sets the request.user @jpadilla? It seems like a common use case unless I'm missing something

**Comment by ArtemBernatskyy** [comment]
+1

**Comment by AndreyBulezyuk** [comment]
+1
