### ISSUE TITLE
Getting error 500 when attempting to pull request

### ISSUE THREAD

**Issue by mathiasose** [GetBlimp/django-rest-framework-jwt#246]
My fork is at https://github.com/mathiasose/django-rest-framework-jwt/commit/a62b8f6595b232dc015190cf32ea2586341ef256

I tried opening a PR on June 10th, didn't work.
Then I forgot about it for a while until today, and it still doesn't work.

If you think this change is OK, feel free to "merge" it manually.

**Comment by MattHardcastle** [comment]
Looking through the comments on open issues it's clear a few people are seeing this 500 error when creating pull requests. I know I am. I submitted a ticket with GitHub on June 21 about it but haven't heard any update after their acknowledgment.

@jpadilla do you have any idea what the issue is? It seems you've been able to accept pull requests in the past.

**Comment by jpadilla** [comment]
@MattHardcastle reported this issue to GitHub. Will update when I have more info.

**Comment by jpadilla** [comment]
This should be resolved.
