### ISSUE TITLE
RS256 and the PUBLIC_KEY

### ISSUE THREAD

**Issue by dbinetti** [GetBlimp/django-rest-framework-jwt#319]
I've been trying to implement the RS256 algorithm for the better part of two days and have nothing to show for it (except for a lot of missing hair where I've pulled it all out.)

I've looked at these docs and code, and PyJWT, and the cryptography library and can't make sense of any of it I'm afraid.  I'm using Auth0, and they tell me my public key is this .PEM file, which despite all my efforts I can't get to be recognized in the JWT_PUBLIC_KEY setting.  How should this be formatted?  Following the `load_pem_x509_certificate` instructions from Mark Adams only produces a `TypeError: initializer for ctype 'char[]' must be a bytes or list or tuple, not str`.  And I could go on in my list of dead-ends, but I'm just hoping for some direction that I've missed...  THanks

**Comment by eavictor** [comment]
Hello dbinetti,
I also bumping into this problem today, but after dig into some old issues #136 #144 #200 
I finally found the solution which is quite simple.

I put the key pair in same folder next to settings.py because of laziness...

Here is my settings.py JWT_AUTH part:
```
# /website/website/settings.py

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

JWT_AUTH = {
    'JWT_PUBLIC_KEY': open(BASE_DIR + '/website/STAR_eavictor_com.crt').read(),
    'JWT_PRIVATE_KEY': open(BASE_DIR + '/website/STAR_eavictor_com.key').read(),
    'JWT_ALGORITHM': 'RS256',
}
```

**Comment by dbinetti** [comment]
Thanks @eavictor , but in my case I don't have access to the private key.  I use Auth0, which keeps the private key private (obviously).  I can get their public key which, IIUC, should allow me to decode the JWT.  I did at last figure out that the public key needs to be read from the bytes (not a sting, which is contrary to what @mark-adams wrote [here](https://github.com/jpadilla/pyjwt/blob/master/docs/faq.rst#how-can-i-extract-a-public--private-key-from-a-x509-certificate)). However, none of these approaches have worked and I remain stuck.

**Comment by mark-adams** [comment]
@dbinetti My instructions were written with Python 2 in mind. In Python 2, the default string type is `str` which is actually an array of bytes. In Python 3, the default string type is `str` which is equivalent to the `unicode` type in Python 2. You can retrieve the bytes instead of unicode from a file in Python 3 by using `open('filename', 'rb')` or by calling the `.encode()` method on the string.

When using `cryptography`, you should take care to understand which version of Python you are using since `cryptography` prefers to work with raw bytes (string in Python 2 or bytes in Python 3). 

The instructions in the FAQ are correct but I could see that it might be helpful to include something explaining they are written with Python 2 in mind.

**Comment by dbinetti** [comment]
Apologies, @mark-adams, I meant no disrespect; indeed, I didn't consider the differences between 2 and 3.  For newbies such as myself this stuff is really, ahem, cryptic, and fundamentals such as the bytes/string can be easily overlooked.  

I will do my part and put in a PR to help the next n00b.
