### ISSUE TITLE
Whats the rationale for deprecating get_user_id_from_payload?

### ISSUE THREAD

**Issue by fergyfresh** [GetBlimp/django-rest-framework-jwt#463]
Why would this not be the default way for getting the instance of the user from the JWT? https://github.com/GetBlimp/django-rest-framework-jwt/blob/master/rest_framework_jwt/utils.py#L70

Otherwise I would need to add an extra index on username that I currently do not have? Doesn't really matter to me as I can look under the hood at the function and use the code that exists in the base function `payload.get('user_id'), but why remove the function?

**Comment by Alex3917** [comment]
The main argument for using the username instead of having the primary key of the user in the payload  is that the latter lets anyone who signs up for an account know how many registered users you have and what your growth rate is.

**Comment by fergyfresh** [comment]
That's a backend only function though...

**Comment by Alex3917** [comment]
Oh I see what you're saying. I mean it makes sense to have that be a setting that points to a function, like all the other settings. No idea why that function would get removed as the default, it's possible the same function is just getting moved somewhere else or something so that's why you're getting warned not to monkey patch it.

**Comment by fergyfresh** [comment]
Ahhh. Its saying use the env var to set the output of that instead of monkey patching that function. got it now.
