### ISSUE TITLE
Multiple tokens and logout

### ISSUE THREAD

**Issue by norbertpy** [GetBlimp/django-rest-framework-jwt#64]
Does this library support multiple tokens for a single user? Let's say, a user authenticate from Web and mobile app at the same time. Does the user get the same token?

How would a `logout` procedure look like? Deleting Token? If so, with single Token per user, the user is logged out of all active sessions (web & mobile) which is not desired.

**Comment by jpadilla** [comment]
Multiple tokens can be possible by implementing a custom `JWT_PAYLOAD_HANDLER`. By default user's wouldn't get an exact same token, since they'll have different expiration times.

`logout` would just be removing the token from the client. Tokens are not stored anywhere in the backend, they are completely stateless. Each request will be authenticated if the token is present and is valid, if it's not present requests won't be authenticated.

Users will be able to login on the web and on a mobile app, those tokens are independent and don't affect each other.

You might want to read a bit more on [authentication with JSON Web Tokens](http://jpadilla.com/search/jwt).

**Comment by norbertpy** [comment]
Thanks a lot.
